#!/usr/bin/python3
#+
# This script is a GIMP plugin that generates a "brushed metal" pattern.
#
# Copyright 2011 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import libgimp2
from libgimp2 import \
    GIMP, \
    pdb, \
    pdb1, \
    pdbpi

def do_effect(the_image, the_drawable) :
    pdb.gimp_image_undo_group_start(the_image.id)
    the_layer = pdb1.gimp_layer_new \
      (
        the_image.id, # image
        pdb1.gimp_drawable_width(the_drawable.id), # width
        pdb1.gimp_drawable_height(the_drawable.id), # height
        GIMP.RGB_IMAGE, # type
        "Brushed Metal", # name
        100, # opacity
        GIMP.LAYER_MODE_NORMAL # mode
      )
    pdb.gimp_image_add_layer(the_image.id, the_layer, -1)
    pdbpi.plug_in_hsv_noise \
      (
        the_image.id, # image
        the_layer, # drawable
        1, # holdness
        0, # hue_distance
        0, # saturation_distance
        226 # value_distance
      )
    pdb.gimp_levels \
      (
        the_layer, # drawable
        GIMP.HISTOGRAM_VALUE, # channel
        0, # low_input
        0, # high_input
        1.0, # gamma
        64, # low_output
        192 # high_output
      )
    pdbpi.plug_in_mblur \
      (
        the_image.id, # image
        the_layer, # drawable
        0, # type = linear
        39, # length
        0, # angle
        0, # center_x,  not relevant for linear blur
        0 # center_y,  not relevant for linear blur
      )
    pdbpi.plug_in_unsharp_mask \
      (
        the_image.id, # image
        the_layer, # drawable
        46, # radius
        1, # amount
        0 # threshold
      )
    pdb.gimp_image_undo_group_end(the_image.id)
#end do_effect

libgimp2.plugin_install \
  (
    name = "python_fu_brushed_metal",
    blurb = "Generate a brushed-metal texture",
    help = "Generates a new image layer filled with the texture.",
    author = "Lawrence D'Oliveiro",
    copyright = "©2011 by Lawrence D’Oliveiro",
    date = "2022 June 2",
    image_types = "RGB*, GRAY*", # same as Gaussian blur
    placement = libgimp2.UI_PLACEMENT.IMAGE,
    action = do_effect,
    params = None,
    return_vals = None,
    item_label = "Brushed Metal",
    menu_name = "/Filters/Render",
  )

libgimp2.main()
