#!/usr/bin/python3
#+
# This script is a GIMP plugin that simulates a Michael Orton effect
# as described on page 77 of the June 2009 issue of Australian PC User
# magazine.
#
# Copyright 2009 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import libgimp2
from libgimp2 import \
    GIMP, \
    PARAMTYPE, \
    pdb, \
    pdb1, \
    pdbpi

def do_effect(the_image, the_drawable, radius) :
    pdb.gimp_image_undo_group_start(the_image)
    active_layer = pdb1.gimp_image_get_active_layer(the_image)
    the_layer = pdb1.gimp_layer_copy(active_layer, False)
    pdb.gimp_image_add_layer(the_image, the_layer, -1)
    pdb.gimp_layer_set_mode(the_layer, GIMP.LAYER_MODE_SCREEN)
    pdb.gimp_image_merge_down(the_image, the_layer, GIMP.CLIP_TO_BOTTOM_LAYER)
    active_layer = pdb1.gimp_image_get_active_layer(the_image)
    the_layer = pdb1.gimp_layer_copy(active_layer, False)
    pdb.gimp_image_add_layer(the_image, the_layer, -1)
    pdbpi.plug_in_gauss_rle(the_image, the_layer, radius, True, True)
    pdb.gimp_layer_set_mode(the_layer, GIMP.LAYER_MODE_MULTIPLY)
    pdb.gimp_image_merge_down(the_image, the_layer, GIMP.CLIP_TO_BOTTOM_LAYER)
    pdb.gimp_image_undo_group_end(the_image)
#end do_effect

libgimp2.plugin_install \
  (
    name = "python_fu_orton",
    blurb = "Ethereal selective blur in the style of photos by Michael Orton",
    help =
        "Works on the whole image (ignores selection). Based on a description"
        " in the June 2009 issue of Australian “PC User” magazine.",
    author = "Lawrence D'Oliveiro",
    copyright = "©2009 by Lawrence D’Oliveiro",
    date = "2022 May 30",
    image_types = "RGB*, GRAY*", # same as Gaussian blur
    placement = libgimp2.UI_PLACEMENT.IMAGE,
    action = do_effect,
    params =
        [
            {
                "type" : PARAMTYPE.FLOAT,
                "name" : "radius",
                "description" : "Blur radius",
                "default" : 6.0,
                "lower" : 0.0,
                "upper" : 20.0,
            },
        ],
    return_vals = None,
    menu_name = "/Filters/Blur",
    item_label = "Orton...",
  )

libgimp2.main()
